probod:
  auth:
    invitation-confirmation-token-validity: 3600
  api:
    cors:
      allowed-origins: 
        - "${APP_URL}"
        - "https://*.railway.app"
  aws:
    access-key-id: "${S3_ACCESS_KEY_ID}"
    secret-access-key: "${S3_SECRET_ACCESS_KEY}"
    endpoint: "${S3_ENDPOINT}"
    bucket: "${S3_BUCKET:probod}"
    region: "${AWS_REGION:us-east-1}"
  openai:
    api-key: "${OPENAI_API_KEY}"
    temperature: 0.1
    model-name: "gpt-4o"
  mailer:
    from-email: "${MAILER_FROM_EMAIL:noreply@getprobo.com}"
    from-name: "${MAILER_FROM_NAME:Probo}"
    smtp:
      host: "${MAILER_SMTP_HOST}"
      port: "${MAILER_SMTP_PORT:587}"
      username: "${MAILER_SMTP_USERNAME}"
      password: "${MAILER_SMTP_PASSWORD}"
      tls: true
  database:
    url: "${DATABASE_URL}"
    max-connections: "${DB_MAX_CONNECTIONS:20}"
    max-idle-connections: "${DB_MAX_IDLE_CONNECTIONS:5}"
    connection-max-lifetime: "${DB_CONNECTION_MAX_LIFETIME:1h}"
  server:
    address: "0.0.0.0:${PORT:8080}"
    read-timeout: "${SERVER_READ_TIMEOUT:30s}"
    write-timeout: "${SERVER_WRITE_TIMEOUT:30s}"
    idle-timeout: "${SERVER_IDLE_TIMEOUT:120s}"
  session:
    secret: "${SESSION_SECRET}"
    secure: true
    http-only: true
    same-site: "lax"
    max-age: "${SESSION_MAX_AGE:86400}"
  logging:
    level: "${LOG_LEVEL:info}"
    format: "json"
  chrome:
    endpoint: "${CHROME_ENDPOINT:http://chrome:9222}"
  uploads:
    max-size: "${UPLOAD_MAX_SIZE:10485760}"
    allowed-extensions: 
      - ".pdf"
      - ".doc"
      - ".docx"
      - ".xls"
      - ".xlsx"
      - ".png"
      - ".jpg"
      - ".jpeg"
      - ".gif"
    path: "${UPLOAD_PATH:/app/uploads}"
  security:
    allowed-hosts: 
      - "${APP_URL}"
      - "*.railway.app"
    csrf-token-length: 32
    rate-limit:
      enabled: true
      requests-per-minute: "${RATE_LIMIT_RPM:100}"